services:
  postgres:
    image: "postgres"
    pull_policy: missing
    container_name: postgres
    ports:
    - "5432"
    environment:
     POSTGRES_PASSWORD: password
  rabbitmq:
    image: "rabbitmq"
    pull_policy: missing
    container_name: rabbitmq
    restart: always
    ports:
    - "5672"
  redis:
    image: "redis/redis-stack-server"
    pull_policy: missing
    container_name: redis
    restart: always
    ports:
    - "6379"
  config-server:
    image: "config-server:1.0.0"
    pull_policy: missing
    container_name: config-server
    ports:
      - "8888"
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      service-registry:
        condition: service_healthy
      zipkin:
        condition: service_started
    environment:
      THC_PATH: "/actuator/health"
      THC_PORT: 8888
  service-registry:
    image: "service-registry:1.0.0"
    pull_policy: missing
    container_name: service-registry
    ports:
      - "8761"
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    environment:
      THC_PATH: "/actuator/health"
      THC_PORT: 8761
    depends_on:
      zipkin:
        condition: service_started
  auth-server:
    image: "auth-server:1.0.0"
    pull_policy: missing
    container_name: auth-server
    ports:
      - "9000"
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    environment:
      THC_PATH: "/actuator/health"
      THC_PORT: 8761
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
  zipkin:
    image: "openzipkin/zipkin"
    container_name: zipkin
    ports:
      - "9411"
  gateway:
     image: "gateway:1.0.0"
     pull_policy: missing
     container_name: gateway
     ports:
       - "8080"
     depends_on:
       service-registry:
         condition: service_healthy
       config-server:
         condition: service_healthy
       zipkin:
         condition: service_started
  order-service:
    image: "order-service:1.0.0"
    pull_policy: missing
    container_name: order-service
    ports:
      - "8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_started
      zipkin:
        condition: service_started
  product-service:
    image: "product-service:1.0.0"
    pull_policy: missing
    container_name: product-service
    ports:
      - "8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started

  shipping-service:
    image: "shipping-service:1.0.0"
    pull_policy: missing
    container_name: shipping-service
    ports:
    - "8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
      rabbitmq:
        condition: service_started