spring:
  application.name: order-service
  jpa.hibernate.ddl-auto: update

management.endpoints.web.exposure.include: health, info, refresh, cache, caches, metrics
logging.level.org.springframework:
  cache: TRACE
  retry: TRACE
  cloud.circuitbreaker: TRACE
server.error.include-message: always

order:
  exchange-name: order-delivered-exchange
  shipping-exchange-name: order-shipping-exchange
  products-api-url: https://httpbin.org/status/503