spring:
  application.name: order-service # for config server
  jpa.hibernate.ddl-auto: update
  config.import: "configserver:http://config-server:8888"

management.endpoints.web.exposure.include: refresh

order:
  exchange-name: order-delivered-exchange
  shipping-exchange-name: order-shipping-exchange
  products-api-url: