spring:
  application.name: product-service
  config.import: "optional:configserver:http://config-server:8888"
management.tracing.sampling.probability: 1.0

product-service.product-names: Spring Application Advisor

