spring:
  cloud.gateway:
    routes:
      - id: product-service
        uri: http://product-service
        predicates:
          - Path=/services/product-service/**
        filters:
          - StripPrefix=2
      - id: order-service
        uri: http://order-service
        predicates:
          - Path=/services/order-service/**
        filters:
          - StripPrefix=2
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://auth-server/oauth2/jwks
eureka.client.serviceUrl.defaultZone: http://service-registry/eureka/
management.zipkin.tracing.endpoint: http://zipkin/api/v2/spans

