spring:
  cloud.gateway:
    discovery.locator.enabled: true
    routes:
      - id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/services/product-service/**
        filters:
          - StripPrefix=2
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/services/order-service/**
        filters:
          - StripPrefix=2
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://auth-server/oauth2/jwks
eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans

