order.products-api-url: http://PRODUCT-SERVICE/api/v1/products

spring:
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://172.17.0.1:9000/oauth2/jwks
  data.redis.host: "redis"
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
  rabbitmq.host: rabbitmq
eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans