shipping.duration: 10000

spring:
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://auth-server/oauth2/jwks
eureka.client.serviceUrl.defaultZone: http://service-registry/eureka/
management.zipkin.tracing.endpoint: http://zipkin/api/v2/spans