spring:
  application.name: config-server
  cloud.config.server.git:
    uri: https://github.com/timosalm/modern-app-arch-spring-cloud
    search-paths:
    - externalized-configuration
    # Helps to identify a misconfigured configuration source quickly
    clone-on-start: true
server.port: 8888
eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
management:
  tracing.sampling.probability: 1
  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans